name: Anime4U
description: A new Anime application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+16

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher_platform_interface: 2.0.3
  url_launcher: 6.0.6
  nb_utils: 4.2.15+1
  animations: 1.1.2
  intl: 0.16.1
  http: 0.13.0
  firebase: ^9.0.1
  firebase_core_platform_interface: 4.0.1
  firebase_core: 1.3.0
  firebase_analytics: 8.1.2

  firebase_crashlytics: 2.0.6
  google_sign_in: 4.5.3
  html: 0.15.0
  share: 0.6.5
#  mobx: ^1.2.1+2
#  yaml: ^3.0.0
  args: ^2.0.0
  flutter_mobx: ^1.1.0+2
  shared_preferences: ^2.0.6
  provider: ^5.0.0
#  flutter_statusbarcolor: 0.2.3
#  simple_animations: 1.3.8
#  flutter_svg: 0.21.0
  connectivity_platform_interface: ^2.0.1
  connectivity: ^3.0.6
  image_picker_platform_interface: 2.1.0
  image_picker_gallery_camera: 0.2.2
  image_picker: 0.7.4
  wakelock: ^0.5.2
  video_player: ^2.0.0
  visibility_detector: ^0.2.0
#  date_utils: ^0.1.0+3
#  flutter_cache_manager: ^3.0.0
  cached_network_image: ^3.0.0
  firebase_messaging: ^10.0.2
  workmanager: ^0.2.3
  flutter_local_notifications: ^6.0.0
#  overlay_support: ^1.2.0
#  xml: ^5.0.0
  image: ^3.0.1
  font_awesome_flutter: ^8.11.0
  async: ^2.4.2
  path_provider: ^2.0.0
  plain_notification_token: ^0.0.1
#  flutter_countdown_timer: ^2.1.0
  flutter_widget_from_html: ^0.6.1
  expansion_tile_card: ^1.1.0
#  amseekbar: ^0.1.2
  modal_bottom_sheet: ^1.0.0+1
#  flutter_downloader: ^1.5.2
  platform: ^3.0.0
  plugin_platform_interface: ^2.0.0
  permission_handler_platform_interface: ^3.6.0
  permission_handler: ^8.0.1
  webview_flutter: ^2.0.4
  package_info: ^0.4.0+16
#  carousel_slider: ^3.0.0
  custom_navigation_bar: ^0.8.2
#  charts_flutter: ^0.9.0
  chewie: ^1.2.2
  better_player: ^0.0.62
  flutter_applovin_max: ^2.0.0
#  settings_ui: ^1.0.0
#  crypto: ^3.0.1
#  native_admob_flutter: ^1.4.1
  laravel_echo: ^0.2.9
  flutter_pusher_client: ^0.3.1
  rating_dialog: ^2.0.0
  loadmore: ^2.0.1
  facebook_audience_network: ^0.9.0
#  flutter_inappwebview: ^5.3.2
#  flutter_downloader: ^1.5.2
#  dio: ^4.0.0

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  color: "#263238"
  image: assets/images/barimage.png
  fill: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/muvi/icons/
    - images/muvi/images/
    - assets/
    - assets/images/
    - lang/en.json
    - lang/hi.json
    - assets/fransisco/regular.otf
    - assets/fransisco/bold.otf
    - assets/fransisco/black.otf
    - assets/monsterrat/Montserrat-Regular.ttf
    - assets/monsterrat/Montserrat-Medium.ttf
    - assets/monsterrat/Montserrat-Bold.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
